# Generated by Django 4.2 on 2024-12-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
