# Generated by Django 4.2 on 2024-12-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0002_joblisting_email_joblisting_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='skills_qualifications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
